FROM node:20-alpine AS builder
WORKDIR /app/xServer
COPY xServer/package*.json ./
RUN npm ci
COPY xServer/ .

FROM node:20-alpine
WORKDIR /app/xServer
COPY --from=builder --chown=node:node /app/xServer ./
COPY --chown=node:node xClient/dist /app/xClient/dist
USER node
EXPOSE 8001
CMD ["node", "server.js"]